{
 "title": "Pechera Inteligente",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Nivel de gas en el ambiente",
   "type": "stat",
   "description": "Este grafico muestra el valor de concentración de gas al que se expone el perro.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ddi01",
     "rawSql": "SELECT value FROM ddi01.sensor_data WHERE sensor=2 "
    }
   ]
  },
  {
   "title": "Nivel de lluvia en el ambiente",
   "type": "gauge",
   "description": "Este grafico muestra el nivel de lluvia al que se expone el perro.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ddi01",
     "rawSql": "SELECT value FROM ddi01.sensor_data WHERE sensor=3"
    }
   ]
  },
  {
   "title": "Temperatura corporal",
   "type": "stat",
   "description": "Este grafico muestra la temperatura corporal del perro.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ddi01",
     "rawSql": "SELECT value FROM ddi01.sensor_data WHERE sensor=4"
    }
   ]
  },
  {
   "title": "Nivel de luz",
   "type": "gauge",
   "description": "Este grafico muestra el nivel de luz al que se expone el perro.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ddi01",
     "rawSql": "SELECT value FROM ddi01.sensor_data WHERE sensor=5"
    }
   ]
  }
 ]
}